
	// var map = new BMap.Map("allmap");    // 创建Map实例
	// var cityName="";	
	// var myCity = new BMap.LocalCity();
	// myCity.get(function myFun(result){
	// 	cityName = result.name;
	// });
	// map.centerAndZoom(cityName,11);
	// console.log(cityName);
	function Goback(){
		$("#tab_main").animate({left:"100%"},"fast",function(){$("#tab_main").css({"display":"none"});});
		$(".weui_tab").css({"overflow":"hidden"});
		$("#tab_body").css({"display":"block"});			
	}

	$("#chooseArea").click(function(){
		var aHtml='<div class="weui_cells" style="position:fixed;width:100%;line-height:44px;height:44px;z-index:999;background:#fff;margin-top:0">'
				+ '    <div class="weui_cell" style="padding-top: 0px;height:44px;">'
				+ '        <span class="back"><a href="javascript:Goback();" style="font-size:16px;color:#159de3;display:block;float:left">Back</a></span>'
				+ '        <div class="weui_cell_bd weui_cell_primary">'
				+ '            <p style=" text-align:center; font-weight:bold;font-size:16px;">ChooseArea</p>'
				+ '        </div>'
				+ '    </div>'
				+ '</div>'

				+'<div class="weui-search-bar" id="searchBar" style="width:94%;margin:50px auto 0;">'
				+'    <form class="weui-search-bar__form">'
				+'        <div class="weui-search-bar__box">'
				+'            <i class="weui-icon-search"></i>'
				+'            <input type="search" class="weui-search-bar__input" id="searchInput" placeholder="城市(如北京/beijing/bj)" required="">'
				+'            <a href="javascript:" class="weui-icon-clear" id="searchClear"></a>'
				+'        </div>'
				+'        <label class="weui-search-bar__label" id="searchText">'
				+'            <i class="weui-icon-search"></i>'
				+'            <span>城市(如北京/beijing/bj)</span>'
				+'        </label>'
				+'    </form>'
				+'    <a href="javascript:" class="weui-search-bar__cancel-btn" id="searchCancel">取消</a>'
				+'</div>'
				+'<div class="weui-cells weui-cells_access search_show" id="search_show">'
	
				+'</div>'							
				
			    +'<div class="container" style="width:100%;position:absolute;top:100px;left:0;background-color:#ffffff;overflow:auto; ">'
				+'    <div class="city" style="width:90%;overflow:hidden;padding:20px;">'
				+'        <div class="city-list"><span class="city-letter" id="A1">A</span>'
				+'            <p data-name="anshan" data-shorten="as" data-id="210300">鞍山市</p>'
				+'            <p data-name="alashanmeng" data-shorten="alsm" data-id="152900">阿拉善盟</p>'
				+'            <p data-name="anqing" data-shorten="aq" data-id="340800">安庆市</p>'
				+'            <p data-name="anyang" data-shorten="ay" data-id="410500">安阳市</p>'
				+'            <p data-name="ali" data-shorten="al" data-id="542500">阿里地区</p>'
			    +'            <p data-name="ankang" data-shorten="ak" data-id="610900">安康市</p>'
				+'            <p data-name="anshun" data-shorten="as" data-id="520400">安顺市</p>'
			    +'            <p data-name="abazangzuqiangzu" data-shorten="abzzqz" data-id="513200">阿坝藏族羌族自治州</p>'
		   	    +'            <p data-name="alaer" data-shorten="ale" data-id="659002">阿拉尔市</p>'
				+'            <p data-name="akesu" data-shorten="aks" data-id="652900">阿克苏地区</p>'
				+'            <p data-name="aomen" data-shorten="am" data-id="820100">澳门特别行政区</p>'
				+'            <p data-name="aletai" data-shorten="alt" data-id="654300">阿勒泰地区</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="B1">B</span>'
				+'            <p data-name="baicheng" data-shorten="bc" data-id="220800">白城市</p>'
				+'            <p data-name="baotou" data-shorten="bt" data-id="150200">包头市</p>'
				+'            <p data-name="bayanzhuoer" data-shorten="byze" data-id="150800">巴彦淖尔市</p>'
				+'            <p data-name="baoding" data-shorten="bd" data-id="130600">保定市</p>'
		        +'            <p data-name="benxi" data-shorten="bx" data-id="210500">本溪市</p>'
			    +'            <p data-name="baishan" data-shorten="bs" data-id="220600">白山市</p>'
				+'            <p data-name="bozhou" data-shorten="bz" data-id="341600">亳州市</p>'
				+'            <p data-name="bangbu" data-shorten="bb" data-id="340300">蚌埠市</p>'
				+'            <p data-name="binzhou" data-shorten="bz" data-id="371600">滨州市</p>'
				+'            <p data-name="baiyin" data-shorten="by" data-id="620400">白银市</p>'
				+'            <p data-name="baoji" data-shorten="bj" data-id="610300">宝鸡市</p>'
				+'            <p data-name="baoshan" data-shorten="bs" data-id="530500">保山市</p>'
				+'            <p data-name="baishalizu" data-shorten="bslz" data-id="469030">白沙黎族自治县</p>'
				+'            <p data-name="baise" data-shorten="bs" data-id="451000">百色市</p>'
				+'            <p data-name="bijie" data-shorten="bj" data-id="522401">毕节市</p>'
				+'            <p data-name="beihai" data-shorten="bh" data-id="450500">北海市</p>'
				+'            <p data-name="bazhong" data-shorten="bz" data-id="511900">巴中市</p>'
				+'            <p data-name="baotinglizumiaozu" data-shorten="btlzmz" data-id="469035">保亭黎族苗族自治县</p>'
				+'            <p data-name="bayinguolengmenggu" data-shorten="byglmg" data-id="652800">巴音郭楞蒙古自治州</p>'
				+'            <p data-name="boertalamenggu" data-shorten="betlmg" data-id="652700">博尔塔拉蒙古自治州</p>'
				+'            <p data-name="beijing" data-shorten="bj" data-id="110100">北京市</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="C1">C</span>'
				+'            <p data-name="changzhi" data-shorten="cz" data-id="140400">长治市</p>'
				+'            <p data-name="cangzhou" data-shorten="cz" data-id="130900">沧州市</p>'
				+'            <p data-name="changzhou" data-shorten="cz" data-id="320400">常州市</p>'
				+'            <p data-name="cixi" data-shorten="cx" data-id="330282">慈溪市</p>'
				+'            <p data-name="changshu" data-shorten="cs" data-id="320581">常熟市</p>'
				+'            <p data-name="chengde" data-shorten="cd" data-id="130800">承德市</p>'
				+'            <p data-name="chifeng" data-shorten="cf" data-id="150400">赤峰市</p>'
				+'            <p data-name="changchun" data-shorten="cc" data-id="220100">长春市</p>'
			    +'            <p data-name="chenzhou" data-shorten="cz" data-id="431000">郴州市</p>'
				+'            <p data-name="changsha" data-shorten="cs" data-id="430100">长沙市</p>'
				+'            <p data-name="chuzhou" data-shorten="cz" data-id="341100">滁州市</p>'
				+'            <p data-name="changde" data-shorten="cd" data-id="430700">常德市</p>'
				+'            <p data-name="chaohu" data-shorten="ch" data-id="341400">巢湖市</p>'
				+'            <p data-name="chizhou" data-shorten="cz" data-id="341700">池州市</p>'
				+'            <p data-name="chengmai" data-shorten="cm" data-id="469027">澄迈县</p>'
				+'            <p data-name="chongzuo" data-shorten="cz" data-id="451400">崇左市</p>'
				+'            <p data-name="changjianglizu" data-shorten="cjlz" data-id="469031">昌江黎族自治县</p>'
				+'            <p data-name="chuxiongyizu" data-shorten="cxyz" data-id="532300">楚雄彝族自治州</p>'
				+'            <p data-name="chaozhou" data-shorten="cz" data-id="445100">潮州市</p>'
				+'            <p data-name="chongqing" data-shorten="cq" data-id="500100">重庆市</p>'
				+'            <p data-name="chengdu" data-shorten="cd" data-id="510100">成都市</p>'
			    +'            <p data-name="changdu" data-shorten="cd" data-id="542100">昌都地区</p>'
				+'            <p data-name="changjihuizu" data-shorten="cjhz" data-id="652300">昌吉回族自治州</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="D1">D</span>'
				+'            <p data-name="daxinganling" data-shorten="dxal" data-id="232700">大兴安岭地区</p>'
				+'            <p data-name="datong" data-shorten="dt" data-id="140200">大同市</p>'
				+'            <p data-name="daqing" data-shorten="dq" data-id="230600">大庆市</p>'
				+'            <p data-name="danyang" data-shorten="dy" data-id="321181">丹阳市</p>'
			    +'            <p data-name="dalian" data-shorten="dl" data-id="210200">大连市</p>'
			    +'            <p data-name="dandong" data-shorten="dd" data-id="210600">丹东市</p>'
			    +'            <p data-name="dongying" data-shorten="dy" data-id="370500">东营市</p>'
			    +'            <p data-name="dezhou" data-shorten="dz" data-id="371400">德州市</p>'
			    +'            <p data-name="dazhou" data-shorten="dz" data-id="511700">达州市</p>'
			    +'            <p data-name="dalibaizu" data-shorten="dlbz" data-id="532900">大理白族自治州</p>'
			    +'            <p data-name="danzhou" data-shorten="dz" data-id="469003">儋州市</p>'
				+'            <p data-name="dingan" data-shorten="da" data-id="469025">定安县</p>'
				+'            <p data-name="diqingzangzu" data-shorten="dqzz" data-id="533400">迪庆藏族自治州</p>'
				+'            <p data-name="deyang" data-shorten="dy" data-id="510600">德阳市</p>'
			    +'            <p data-name="dongfang" data-shorten="df" data-id="469007">东方市</p>'
				+'            <p data-name="dehongdaizujingpozu" data-shorten="dhdzjpz" data-id="533100">德宏傣族景颇族自治州</p>'
				+'            <p data-name="dongguan" data-shorten="dg" data-id="441900">东莞市</p>'
				+'            <p data-name="dingxi" data-shorten="dx" data-id="621100">定西市</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="E1">E</span>'
				+'            <p data-name="eerduosi" data-shorten="eeds" data-id="150600">鄂尔多斯市</p>'
				+'            <p data-name="ezhou" data-shorten="ez" data-id="420700">鄂州市</p>'
				+'            <p data-name="enshitujiazumiaozu" data-shorten="estjzmz" data-id="422800">恩施土家族苗族自治州</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="F1">F</span>'
				+'            <p data-name="fuxin" data-shorten="fx" data-id="210900">阜新市</p>'
				+'            <p data-name="fushun" data-shorten="fs" data-id="210400">抚顺市</p>'
				+'            <p data-name="fuqing" data-shorten="fq" data-id="350181">福清市</p>'
				+'            <p data-name="fuyang" data-shorten="fy" data-id="341200">阜阳市</p>'
				+'            <p data-name="feicheng" data-shorten="fc" data-id="370983">肥城市</p>'
				+'            <p data-name="fuzhou" data-shorten="fz" data-id="361000">抚州市</p>'
				+'            <p data-name="fuzhou" data-shorten="fz" data-id="350100">福州市</p>'
				+'            <p data-name="foshan" data-shorten="fs" data-id="440600">佛山市</p>'
				+'            <p data-name="fangchenggang" data-shorten="fcg" data-id="450600">防城港市</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="G1">G</span>'
				+'            <p data-name="guangzhou" data-shorten="gz" data-id="440100">广州市</p>'
				+'            <p data-name="ganzhou" data-shorten="gz" data-id="360700">赣州市</p>'
			    +'            <p data-name="guangyuan" data-shorten="gy" data-id="510800">广元市</p>'
				+'            <p data-name="guangan" data-shorten="ga" data-id="511600">广安市</p>'
				+'            <p data-name="guilin" data-shorten="gl" data-id="450300">桂林市</p>'
				+'            <p data-name="guigang" data-shorten="gg" data-id="450800">贵港市</p>'
				+'            <p data-name="guiyang" data-shorten="gy" data-id="520100">贵阳市</p>'
				+'            <p data-name="ganzizangzu" data-shorten="gzzz" data-id="513300">甘孜藏族自治州</p>'
				+'            <p data-name="gannanzangzu" data-shorten="gnzz" data-id="623000">甘南藏族自治州</p>'
				+'            <p data-name="guyuan" data-shorten="gy" data-id="640400">固原市</p>'
				+'            <p data-name="guoluozangzu" data-shorten="glzz" data-id="632600">果洛藏族自治州</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="H1">H</span>'
				+'            <p data-name="heihe" data-shorten="hh" data-id="231100">黑河市</p>'
			    +'            <p data-name="huludao" data-shorten="hld" data-id="211400">葫芦岛市</p>'
				+'            <p data-name="haining" data-shorten="hn" data-id="330481">海宁市</p>'
				+'            <p data-name="huaian" data-shorten="ha" data-id="320800">淮安市</p>'
				+'            <p data-name="hengshui" data-shorten="hs" data-id="131100">衡水市</p>'
				+'            <p data-name="huhehaote" data-shorten="hhht" data-id="150100">呼和浩特市</p>'
				+'            <p data-name="huzhou" data-shorten="hz" data-id="330500">湖州市</p>'
				+'            <p data-name="hegang" data-shorten="hg" data-id="230400">鹤岗市</p>'
				+'            <p data-name="hulunbeier" data-shorten="hlbe" data-id="150700">呼伦贝尔市</p>'
				+'            <p data-name="haerbin" data-shorten="heb" data-id="230100">哈尔滨市</p>'
				+'            <p data-name="handan" data-shorten="hd" data-id="130400">邯郸市</p>'
				+'            <p data-name="hangzhou" data-shorten="hz" data-id="330100">杭州市</p>'
				+'            <p data-name="hebi" data-shorten="hb" data-id="410600">鹤壁市</p>'
				+'            <p data-name="heze" data-shorten="hz" data-id="371700">菏泽市</p>'
				+'            <p data-name="huangshi" data-shorten="hs" data-id="420200">黄石市</p>'
				+'            <p data-name="huaihua" data-shorten="hh" data-id="431200">怀化市</p>'
				+'            <p data-name="huaibei" data-shorten="hb" data-id="340600">淮北市</p>'
				+'            <p data-name="huanggang" data-shorten="hg" data-id="421100">黄冈市</p>'
				+'            <p data-name="hengyang" data-shorten="hy" data-id="430400">衡阳市</p>'
				+'            <p data-name="hefei" data-shorten="hf" data-id="340100">合肥市</p>'
				+'            <p data-name="huainan" data-shorten="hn" data-id="340400">淮南市</p>'
				+'            <p data-name="huangshan" data-shorten="hs" data-id="341000">黄山市</p>'
				+'            <p data-name="hechi" data-shorten="hc" data-id="451200">河池市</p>'
				+'            <p data-name="haikou" data-shorten="hk" data-id="460100">海口市</p>'
				+'            <p data-name="heyuan" data-shorten="hy" data-id="441600">河源市</p>'
				+'            <p data-name="honghehanizuyizu" data-shorten="hhhnzyz" data-id="532500">红河哈尼族彝族自治州</p>'
				+'            <p data-name="huizhou" data-shorten="hz" data-id="441300">惠州市</p>'
				+'            <p data-name="hanzhong" data-shorten="hz" data-id="610700">汉中市</p>'
				+'            <p data-name="hezhou" data-shorten="hz" data-id="451100">贺州市</p>'
				+'            <p data-name="haiximengguzuzangzu" data-shorten="hxmgzzz" data-id="632800">海西蒙古族藏族自治州</p>'
				+'            <p data-name="haidong" data-shorten="hd" data-id="632100">海东市</p>'
				+'            <p data-name="huangnanzangzu" data-shorten="hnzz" data-id="632300">黄南藏族自治州</p>'
				+'            <p data-name="hami" data-shorten="hm" data-id="652200">哈密地区</p>'
				+'            <p data-name="haibeizangzu" data-shorten="hbzz" data-id="632200">海北藏族自治州</p>'
				+'            <p data-name="hetian" data-shorten="ht" data-id="653200">和田地区</p>'
				+'            <p data-name="hainanzangzu" data-shorten="hnzz" data-id="632500">海南藏族自治州</p>'
				+'        </div>'
				+'       <div class="city-list"><span class="city-letter" id="J1">J</span>'
				+'            <p data-name="jinzhou" data-shorten="jz" data-id="210700">锦州市</p>'
				+'            <p data-name="jinhua" data-shorten="jh" data-id="330700">金华市</p>'
				+'            <p data-name="jinzhong" data-shorten="jz" data-id="140700">晋中市</p>'
				+'            <p data-name="jiangyin" data-shorten="jy" data-id="320281">江阴市</p>'
				+'            <p data-name="jilin" data-shorten="jl" data-id="220200">吉林市</p>'
				+'            <p data-name="jiamusi" data-shorten="jms" data-id="230800">佳木斯市</p>'
				+'            <p data-name="jixi" data-shorten="jx" data-id="230300">鸡西市</p>'
				+'            <p data-name="jiaxing" data-shorten="jx" data-id="330400">嘉兴市</p>'
				+'            <p data-name="jincheng" data-shorten="jc" data-id="140500">晋城市</p>'
				+'            <p data-name="jinjiang" data-shorten="jj" data-id="350582">晋江市</p>'
				+'            <p data-name="jimo" data-shorten="jm" data-id="370282">即墨市</p>'
				+'            <p data-name="jian" data-shorten="ja" data-id="360800">吉安市</p>'
				+'            <p data-name="jinan" data-shorten="jn" data-id="370100">济南市</p>'
				+'            <p data-name="jingmen" data-shorten="jm" data-id="420800">荆门市</p>'
				+'            <p data-name="jiaozuo" data-shorten="jz" data-id="410800">焦作市</p>'
				+'            <p data-name="jining" data-shorten="jn" data-id="370800">济宁市</p>'
			    +'            <p data-name="jiyuan" data-shorten="jy" data-id="410881">济源市</p>'
			    +'            <p data-name="jingzhou" data-shorten="jz" data-id="421000">荆州市</p>'
				+'            <p data-name="jiujiang" data-shorten="jj" data-id="360400">九江市</p>'
				+'            <p data-name="jingdezhen" data-shorten="jdz" data-id="360200">景德镇市</p>'
				+'            <p data-name="jieyang" data-shorten="jy" data-id="445200">揭阳市</p>'
				+'            <p data-name="jinchang" data-shorten="jc" data-id="620300">金昌市</p>'
				+'            <p data-name="jiangmen" data-shorten="jm" data-id="440700">江门市</p>'
				+'            <p data-name="jiayuguan" data-shorten="jyg" data-id="620200">嘉峪关市</p>'
				+'            <p data-name="jiuquan" data-shorten="jq" data-id="620900">酒泉市</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="K1">K</span>'
				+'            <p data-name="kunshan" data-shorten="ks" data-id="320583">昆山市</p>'
				+'            <p data-name="kaifeng" data-shorten="kf" data-id="410200">开封市</p>'
				+'            <p data-name="kunming" data-shorten="km" data-id="530100">昆明市</p>'
				+'            <p data-name="kelamayi" data-shorten="klmy" data-id="650200">克拉玛依市</p>'
				+'            <p data-name="kwzilesukeerkezi" data-shorten="kzlskekz" data-id="653000">克孜勒苏柯尔克孜自治州</p>'
				+'            <p data-name="keshi" data-shorten="ks" data-id="653100">喀什地区</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="L1">L</span>'
				+'            <p data-name="linfen" data-shorten="lf" data-id="141000">临汾市</p>'
				+'            <p data-name="langfang" data-shorten="lf" data-id="131000">廊坊市</p>'
				+'            <p data-name="liaoyang" data-shorten="ly" data-id="211000">辽阳市</p>'
				+'            <p data-name="liaoyuan" data-shorten="ly" data-id="220400">辽源市</p>'
				+'            <p data-name="luliang" data-shorten="ll" data-id="141100">吕梁市</p>'
				+'            <p data-name="lianyungang" data-shorten="lyg" data-id="320700">连云港市</p>'
				+'            <p data-name="laiwu" data-shorten="lw" data-id="371200">莱芜市</p>'
				+'            <p data-name="luohe" data-shorten="lh" data-id="411100">漯河市</p>'
				+'            <p data-name="lishui" data-shorten="ls" data-id="331100">丽水市</p>'
				+'            <p data-name="liuan" data-shorten="la" data-id="341500">六安市</p>'
				+'            <p data-name="loudi" data-shorten="ld" data-id="431300">娄底市</p>'
				+'            <p data-name="longyan" data-shorten="ly" data-id="350800">龙岩市</p>'
				+'            <p data-name="longkou" data-shorten="lk" data-id="370681">龙口市</p>'
				+'            <p data-name="linqi" data-shorten="lf" data-id="371300">临沂市</p>'
				+'            <p data-name="luoyang" data-shorten="ly" data-id="410300">洛阳市</p>'
				+'            <p data-name="liaocheng" data-shorten="lc" data-id="371500">聊城市</p>'
				+'            <p data-name="lijiang" data-shorten="lj" data-id="530700">丽江市</p>'
				+'            <p data-name="laibin" data-shorten="lb" data-id="451300">来宾市</p>'
				+'            <p data-name="luzhou" data-shorten="lz" data-id="510500">泸州市</p>'
				+'            <p data-name="lincang" data-shorten="lc" data-id="530900">临沧市</p>'
				+'            <p data-name="ledonglizu" data-shorten="ldlz" data-id="469033">乐东黎族自治县</p>'
				+'            <p data-name="leshan" data-shorten="ls" data-id="511100">乐山市</p>'
				+'            <p data-name="lanzhou" data-shorten="lz" data-id="620100">兰州市</p>'
				+'            <p data-name="liuzhou" data-shorten="lz" data-id="450200">柳州市</p>'
				+'            <p data-name="liangshanyizu" data-shorten="lsyz" data-id="513400">凉山彝族自治州</p>'
				+'            <p data-name="lingshuilizu" data-shorten="lslz" data-id="469034">陵水黎族自治县</p>'
				+'            <p data-name="linzhi" data-shorten="lz" data-id="542600">林芝地区</p>'
				+'            <p data-name="lingao" data-shorten="lg" data-id="469028">临高县</p>'
				+'            <p data-name="lasa" data-shorten="ls" data-id="540100">拉萨市</p>'
				+'            <p data-name="liupanshui" data-shorten="lps" data-id="520200">六盘水市</p>'
				+'            <p data-name="longnan" data-shorten="ln" data-id="621200">陇南市</p>'
				+'            <p data-name="linxiahuizu" data-shorten="lxhz" data-id="622900">临夏回族自治州</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="M1">M</span>'
				+'            <p data-name="mudanjiang" data-shorten="mdj" data-id="231000">牡丹江市</p>'
				+'            <p data-name="maanshan" data-shorten="mas" data-id="340500">马鞍山市</p>'
				+'            <p data-name="mianyang" data-shorten="my" data-id="510700">绵阳市</p>'
				+'            <p data-name="meishan" data-shorten="ms" data-id="511400">眉山市</p>'
				+'            <p data-name="maoming" data-shorten="mm" data-id="440900">茂名市</p>'
				+'            <p data-name="meizhou" data-shorten="mz" data-id="441400">梅州市</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="N1">N</span>'
				+'            <p data-name="nanjing" data-shorten="nj" data-id="320100">南京市</p>'
				+'            <p data-name="ningbo" data-shorten="nb" data-id="330200">宁波市</p>'
				+'            <p data-name="nantong" data-shorten="nt" data-id="320600">南通市</p>'
				+'            <p data-name="nanchang" data-shorten="nc" data-id="360100">南昌市</p>'
				+'            <p data-name="nanyang" data-shorten="ny" data-id="411300">南阳市</p>'
				+'            <p data-name="nanping" data-shorten="np" data-id="350700">南平市</p>'
				+'            <p data-name="ningde" data-shorten="nd" data-id="350900">宁德市</p>'
				+'            <p data-name="nanan" data-shorten="na" data-id="350583">南安市</p>'
				+'            <p data-name="naqu" data-shorten="nq" data-id="542400">那曲地区</p>'
				+'            <p data-name="nanning" data-shorten="nn" data-id="450100">南宁市</p>'
				+'            <p data-name="nanchong" data-shorten="nc" data-id="511300">南充市</p>'
				+'            <p data-name="neijiang" data-shorten="nj" data-id="511000">内江市</p>'
				+'            <p data-name="nujianglisuzu" data-shorten="njlsz" data-id="533300">怒江傈僳族自治州</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="P1">P</span>'
				+'            <p data-name="panjing" data-shorten="pj" data-id="211100">盘锦市</p>'
				+'            <p data-name="pingxiang" data-shorten="px" data-id="360300">萍乡市</p>'
				+'            <p data-name="pingdingshan" data-shorten="pds" data-id="410400">平顶山市</p>'
				+'            <p data-name="puyang" data-shorten="py" data-id="410900">濮阳市</p>'
				+'            <p data-name="putian" data-shorten="pt" data-id="350300">莆田市</p>'
				+'            <p data-name="panzhihua" data-shorten="pzh" data-id="510400">攀枝花市</p>'
				+'            <p data-name="puer" data-shorten="pe" data-id="530800">普洱市</p>'
				+'            <p data-name="pingliang" data-shorten="pl" data-id="620800">平凉市</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="Q1">Q</span>'
				+'            <p data-name="qinhuangdao" data-shorten="qhd" data-id="130300">秦皇岛市</p>'
				+'            <p data-name="qiqihaer" data-shorten="qqhe" data-id="230200">齐齐哈尔市</p>'
				+'            <p data-name="qitaihe" data-shorten="qth" data-id="230900">七台河市</p>'
				+'            <p data-name="quanzhou" data-shorten="qz" data-id="350500">泉州市</p>'
				+'            <p data-name="qianjiang" data-shorten="qj" data-id="429005">潜江市</p>'
				+'            <p data-name="qingdao" data-shorten="qd" data-id="370200">青岛市</p>'
				+'            <p data-name="quzhou" data-shorten="qz" data-id="330800">衢州市</p>'
				+'            <p data-name="qingyuan" data-shorten="qy" data-id="441800">清远市</p>'
				+'            <p data-name="qiannanbuyizumiaozu" data-shorten="qnbyzmz" data-id="522700">黔南布依族苗族自治州</p>'
				+'            <p data-name="qinzhou" data-shorten="qz" data-id="450700">钦州市</p>'
				+'            <p data-name="qujing" data-shorten="qj" data-id="530300">曲靖市</p>'
				+'            <p data-name="qianxinanbuyizumiaozu" data-shorten="qxnbyzmz" data-id="522300">黔西南布依族苗族自治州</p>'
				+'            <p data-name="qingyang" data-shorten="qy" data-id="621000">庆阳市</p>'
				+'            <p data-name="qiandongnanmiaozutongzu" data-shorten="qdnmztz" data-id="522600">黔东南苗族侗族自治州</p>'
				+'            <p data-name="qionghai" data-shorten="qh" data-id="469002">琼海市</p>'
				+'            <p data-name="qiongzhonglizumiaozu" data-shorten="qzlzmz" data-id="469036">琼中黎族苗族自治县</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="R1">R</span>'
				+'            <p data-name="rugao" data-shorten="rg" data-id="320682">如皋市</p>'
				+'            <p data-name="rongcheng" data-shorten="rc" data-id="371082">荣成市</p>'
				+'            <p data-name="rizhao" data-shorten="rz" data-id="371100">日照市</p>'
				+'            <p data-name="rikeze" data-shorten="rkz" data-id="542301">日喀则市</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="S1">S</span>'
			    +'            <p data-name="siping" data-shorten="sp" data-id="220300">四平市</p>'
			    +'            <p data-name="suihua" data-shorten="sh" data-id="231200">绥化市</p>'
			    +'            <p data-name="songyuan" data-shorten="sy" data-id="220700">松原市</p>'
			    +'            <p data-name="suzhou" data-shorten="sz" data-id="320500">苏州市</p>'
			    +'            <p data-name="shanghai" data-shorten="sh" data-id="310100">上海市</p>'
				+'            <p data-name="suqian" data-shorten="sq" data-id="321300">宿迁市</p>'
			    +'            <p data-name="shaoxing" data-shorten="sx" data-id="330600">绍兴市</p>'
			    +'            <p data-name="shuozhou" data-shorten="sz" data-id="140600">朔州市</p>'
			    +'            <p data-name="shuangyashan" data-shorten="sys" data-id="230500">双鸭山市</p>'
			    +'            <p data-name="shenyang" data-shorten="sy" data-id="210100">沈阳市</p>'
			    +'            <p data-name="shangyu" data-shorten="sy" data-id="330682">上虞市</p>'
			    +'            <p data-name="shijiazhuang" data-shorten="sjz" data-id="130100">石家庄市</p>'
			    +'            <p data-name="shantou" data-shorten="st" data-id="440500">汕头市</p>'
			    +'            <p data-name="sanming" data-shorten="sm" data-id="350400">三明市</p>'
			    +'            <p data-name="shennongjialinqu" data-shorten="snjlq" data-id="429021">神农架林区</p>'
			    +'            <p data-name="shangrao" data-shorten="sr" data-id="361100">上饶市</p>'
			    +'            <p data-name="shangqiu" data-shorten="sq" data-id="411400">商丘市</p>'
			    +'            <p data-name="suizhou" data-shorten="sz" data-id="421300">随州市</p>'
			    +'            <p data-name="suzhou" data-shorten="sz" data-id="341300">宿州市</p>'
			    +'            <p data-name="sanmenxia" data-shorten="smx" data-id="411200">三门峡市</p>'
			    +'            <p data-name="shiyan" data-shorten="sy" data-id="420300">十堰市</p>'
			    +'            <p data-name="shenzhen" data-shorten="sz" data-id="440300">深圳市</p>'
			    +'            <p data-name="shaoyang" data-shorten="sy" data-id="430500">邵阳市</p>'
			    +'            <p data-name="shaoguan" data-shorten="sg" data-id="440200">韶关市</p>'
			    +'            <p data-name="shanwei" data-shorten="sw" data-id="441500">汕尾市</p>'
			    +'            <p data-name="suining" data-shorten="sn" data-id="510900">遂宁市</p>'
			    +'            <p data-name="shangluo" data-shorten="sl" data-id="611000">商洛市</p>'
			    +'            <p data-name="shangnan" data-shorten="sn" data-id="542200">山南地区</p>'
			    +'            <p data-name="sanya" data-shorten="sy" data-id="460200">三亚市</p>'
			    +'            <p data-name="shizuishan" data-shorten="szs" data-id="640200">石嘴山市</p>'
			    +'            <p data-name="shihezi" data-shorten="shz" data-id="659001">石河子市</p>'
				+'         </div>'
				+'         <div class="city-list"><span class="city-letter" id="T1">T</span>'
				+'            <p data-name="taiyuan" data-shorten="ty" data-id="140100">太原市</p>'
				+'            <p data-name="tieling" data-shorten="tl" data-id="211200">铁岭市</p>'
				+'            <p data-name="tonghua" data-shorten="th" data-id="220500">通化市</p>'
				+'            <p data-name="tangshan" data-shorten="ts" data-id="130200">唐山市</p>'
				+'            <p data-name="taicang" data-shorten="tc" data-id="320585">太仓市</p>'
				+'            <p data-name="tianjin" data-shorten="tj" data-id="120100">天津市</p>'
				+'            <p data-name="taizhou" data-shorten="tz" data-id="321200">泰州市</p>'
				+'            <p data-name="tongliao" data-shorten="tl" data-id="150500">通辽市</p>'
				+'            <p data-name="taizhou" data-shorten="tz" data-id="331000">台州市</p>'
				+'            <p data-name="taian" data-shorten="ta" data-id="370900">泰安市</p>'
				+'            <p data-name="tianmen" data-shorten="tm" data-id="429006">天门市</p>'
				+'            <p data-name="tongling" data-shorten="tl" data-id="340700">铜陵市</p>'
				+'            <p data-name="tongren" data-shorten="tr" data-id="522201">铜仁市</p>'
				+'            <p data-name="tunchang" data-shorten="tc" data-id="469026">屯昌县</p>'
				+'            <p data-name="tongchuan" data-shorten="tc" data-id="610200">铜川市</p>'
				+'            <p data-name="tianshui" data-shorten="ts" data-id="620500">天水市</p>'
				+'            <p data-name="tacheng" data-shorten="tc" data-id="654200">塔城地区</p>'
				+'            <p data-name="tumushuke" data-shorten="tmsk" data-id="659003">图木舒克市</p>'
				+'            <p data-name="tulufan" data-shorten="tlf" data-id="652100">吐鲁番地区</p>'
				+'            <p data-name="taiwan" data-shorten="tw" data-id="710100">台湾</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="W1">W</span>'
				+'            <p data-name="wenzhou" data-shorten="wz" data-id="330300">温州市</p>'
				+'            <p data-name="wuxi" data-shorten="wx" data-id="320200">无锡市</p>'
				+'            <p data-name="wulanzhaibu" data-shorten="wlcb" data-id="150900">乌兰察布市</p>'
				+'            <p data-name="wuhai" data-shorten="wh" data-id="150300">乌海市</p>'
				+'            <p data-name="wuhu" data-shorten="wh" data-id="340200">芜湖市</p>'
				+'            <p data-name="wuhan" data-shorten="wh" data-id="420100">武汉市</p>'
				+'            <p data-name="weifang" data-shorten="wf" data-id="370700">潍坊市</p>'
				+'            <p data-name="weihai" data-shorten="wh" data-id="371000">威海市</p>'
				+'            <p data-name="wanning" data-shorten="wn" data-id="469006">万宁市</p>'
				+'            <p data-name="weinan" data-shorten="wn" data-id="610500">渭南市</p>'
				+'            <p data-name="wenchang" data-shorten="wc" data-id="469005">文昌市</p>'
				+'            <p data-name="wuzhishan" data-shorten="wzs" data-id="469001">五指山市</p>'
				+'            <p data-name="wuwei" data-shorten="ww" data-id="620600">武威市</p>'
				+'            <p data-name="wuzhou" data-shorten="wz" data-id="450400">梧州市</p>'
				+'            <p data-name="wenshanzhuangzumiaozu" data-shorten="wszzmz" data-id="532600">文山壮族苗族自治州</p>'
				+'            <p data-name="wujiaqu" data-shorten="wjq" data-id="659004">五家渠市</p>'
				+'            <p data-name="wuzhong" data-shorten="wz" data-id="640300">吴忠市</p>'
				+'            <p data-name="wulumuqi" data-shorten="wlmq" data-id="650100">乌鲁木齐市</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="X1">X</span>'
				+'            <p data-name="xinzhou" data-shorten="xz" data-id="140900">忻州市</p>'
				+'            <p data-name="xilinguolemeng" data-shorten="xlglm" data-id="152500">锡林郭勒盟</p>'
				+'            <p data-name="xingtai" data-shorten="xt" data-id="130500">邢台市</p>'
				+'            <p data-name="xinganmeng" data-shorten="xam" data-id="152200">兴安盟</p>'
				+'            <p data-name="xuzhou" data-shorten="xz" data-id="320300">徐州市</p>'
				+'            <p data-name="xinxiang" data-shorten="xx" data-id="410700">新乡市</p>'
				+'            <p data-name="xiangyang" data-shorten="xy" data-id="420600">襄阳市</p>'
				+'            <p data-name="xinyu" data-shorten="xy" data-id="360500">新余市</p>'
				+'            <p data-name="xinyang" data-shorten="xy" data-id="411500">信阳市</p>'
				+'            <p data-name="xiantao" data-shorten="xt" data-id="429004">仙桃市</p>'
				+'            <p data-name="xuchang" data-shorten="xc" data-id="411000">许昌市</p>'
				+'            <p data-name="xiangtan" data-shorten="xt" data-id="430300">湘潭市</p>'
				+'            <p data-name="xiamen" data-shorten="xm" data-id="350200">厦门市</p>'
				+'            <p data-name="xuancheng" data-shorten="xc" data-id="341800">宣城市</p>'
				+'            <p data-name="xiaogan" data-shorten="xg" data-id="420900">孝感市</p>'
				+'            <p data-name="xianning" data-shorten="xn" data-id="421200">咸宁市</p>'
				+'            <p data-name="xiangxitujiazumiaozu" data-shorten="xxtjzmz" data-id="433100">湘西土家族苗族自治州</p>'
				+'            <p data-name="xian" data-shorten="xa" data-id="610100">西安市</p>'
				+'            <p data-name="xianyang" data-shorten="xy" data-id="610400">咸阳市</p>'
				+'            <p data-name="xishungbannadaizu" data-shorten="xsbndz" data-id="532800">西双版纳傣族自治州</p>'
				+'            <p data-name="xining" data-shorten="xn" data-id="630100">西宁市</p>'
				+'            <p data-name="xianggang" data-shorten="xg" data-id="810100">香港特别行政区</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="Y1">Y</span>'
				+'            <p data-name="yixing" data-shorten="yx" data-id="320282">宜兴市</p>'
				+'            <p data-name="yanbianchaoxianzu" data-shorten="ybcxz" data-id="222400">延边朝鲜族自治州</p>'
				+'            <p data-name="yangzhou" data-shorten="yz" data-id="321000">扬州市</p>'
				+'            <p data-name="yuncheng" data-shorten="yc" data-id="140800">运城市</p>'
				+'            <p data-name="yancheng" data-shorten="yc" data-id="320900">盐城市</p>'
				+'            <p data-name="yangquan" data-shorten="yq" data-id="140300">阳泉市</p>'
				+'            <p data-name="yuyao" data-shorten="yy" data-id="330281">余姚市</p>'
				+'            <p data-name="yichun" data-shorten="yc" data-id="230700">伊春市</p>'
				+'            <p data-name="yingkou" data-shorten="yk" data-id="210800">营口市</p>'
				+'            <p data-name="yantai" data-shorten="yt" data-id="370600">烟台市</p>'
				+'            <p data-name="yichang" data-shorten="yc" data-id="420500">宜昌市</p>'
				+'            <p data-name="yueyang" data-shorten="yy" data-id="430600">岳阳市</p>'
				+'            <p data-name="yichun" data-shorten="yc" data-id="360900">宜春市</p>'
				+'            <p data-name="yiyang" data-shorten="yy" data-id="430900">益阳市</p>'
				+'            <p data-name="yiwu" data-shorten="yw" data-id="330782">义乌市</p>'
				+'            <p data-name="yingtan" data-shorten="yt" data-id="360600">鹰潭市</p>'
				+'            <p data-name="yongzhou" data-shorten="yz" data-id="431100">永州市</p>'
				+'            <p data-name="yulin" data-shorten="yl" data-id="450900">玉林市</p>'
				+'            <p data-name="yaan" data-shorten="ya" data-id="511800">雅安市</p>'
				+'            <p data-name="yuxi" data-shorten="yx" data-id="530400">玉溪市</p>'
			    +'            <p data-name="yangjiang" data-shorten="yj" data-id="441700">阳江市</p>'
				+'            <p data-name="yulin" data-shorten="yl" data-id="610800">榆林市</p>'
				+'            <p data-name="yibin" data-shorten="yb" data-id="511500">宜宾市</p>'
				+'            <p data-name="yunfu" data-shorten="yf" data-id="445300">云浮市</p>'
				+'            <p data-name="yanan" data-shorten="ya" data-id="610600">延安市</p>'
				+'            <p data-name="yilihasake" data-shorten="ylhsk" data-id="654000">伊犁哈萨克自治州</p>'
				+'            <p data-name="yinchuan" data-shorten="yc" data-id="640100">银川市</p>'
				+'            <p data-name="yushuzangzu" data-shorten="yszz" data-id="632700">玉树藏族自治州</p>'
				+'        </div>'
				+'        <div class="city-list"><span class="city-letter" id="Z1">Z</span>'
				+'            <p data-name="zhangjiakou" data-shorten="zjk" data-id="130700">张家口市</p>'
				+'            <p data-name="zhuji" data-shorten="zj" data-id="330681">诸暨市</p>'
				+'            <p data-name="zhenjiang" data-shorten="zj" data-id="321100">镇江市</p>'
				+'            <p data-name="zhangjiagang" data-shorten="zjg" data-id="320582">张家港市</p>'
				+'            <p data-name="zhaoyang" data-shorten="zy" data-id="211300">朝阳市</p>'
				+'            <p data-name="zhangjiajie" data-shorten="zjj" data-id="430800">张家界市</p>'
				+'            <p data-name="zhengzhou" data-shorten="zz" data-id="410100">郑州市</p>'
				+'            <p data-name="zaozhuang" data-shorten="zz" data-id="370400">枣庄市</p>'
				+'            <p data-name="zhoushan" data-shorten="zs" data-id="330900">舟山市</p>'
				+'            <p data-name="zengcheng" data-shorten="zc" data-id="440183">增城市</p>'
				+'            <p data-name="zhuhai" data-shorten="zh" data-id="440400">珠海市</p>'
				+'            <p data-name="zhoukou" data-shorten="zk" data-id="411600">周口市</p>'
				+'            <p data-name="zibo" data-shorten="zb" data-id="370300">淄博市</p>'
				+'            <p data-name="zhuzhou" data-shorten="zz" data-id="430200">株洲市</p>'
				+'            <p data-name="zhangzhou" data-shorten="zz" data-id="350600">漳州市</p>'
				+'            <p data-name="zhumadian" data-shorten="zmd" data-id="411700">驻马店市</p>'
				+'            <p data-name="zhanjiang" data-shorten="zj" data-id="440800">湛江市</p>'
				+'            <p data-name="zunyi" data-shorten="zy" data-id="520300">遵义市</p>'
				+'            <p data-name="zigong" data-shorten="zg" data-id="510300">自贡市</p>'
				+'            <p data-name="zhaotong" data-shorten="zt" data-id="530600">昭通市</p>'
				+'            <p data-name="zhaoqing" data-shorten="zq" data-id="441200">肇庆市</p>'
				+'            <p data-name="zhongshan" data-shorten="zs" data-id="442000">中山市</p>'
				+'            <p data-name="zhangye" data-shorten="zy" data-id="620700">张掖市</p>'
				+'            <p data-name="ziyang" data-shorten="zy" data-id="512000">资阳市</p>'
				+'            <p data-name="zhongwei" data-shorten="zw" data-id="640500">中卫市</p>'
				+'        </div>'
			    +'    </div>'
			    +'    <div class="letter" style="width:5%;overflow:hidden;line-height: normal;position:fixed;top:100px;right:10px;text-align:center;">'
			    +'        <ul>'
				+'            <li><a href="#A1">A</a></li>'
				+'            <li><a href="#B1">B</a></li>'
				+'            <li><a href="#C1">C</a></li>'
				+'            <li><a href="#D1">D</a></li>'
				+'            <li><a href="#E1">E</a></li>'
			    +'            <li><a href="#F1">F</a></li>'
				+'            <li><a href="#G1">G</a></li>'
				+'            <li><a href="#H1">H</a></li>'
				+'            <li><a href="#J1">J</a></li>'
				+'            <li><a href="#K1">K</a></li>'
				+'            <li><a href="#L1">L</a></li>'
				+'            <li><a href="#M1">M</a></li>'
				+'            <li><a href="#N1">N</a></li>'
				+'            <li><a href="#P1">P</a></li>'
				+'            <li><a href="#Q1">Q</a></li>'
				+'            <li><a href="#R1">R</a></li>'
				+'            <li><a href="#S1">S</a></li>'
				+'            <li><a href="#T1">T</a></li>'
				+'            <li><a href="#W1">W</a></li>'
				+'            <li><a href="#X1">X</a></li>'
				+'            <li><a href="#Y1">Y</a></li>'
				+'            <li><a href="#Z1">Z</a></li>'
				+'        </ul>'
			    +'    </div>'
			    +'</div>'
						
		$(".weui_tab").css({"overflow":"auto"});
		$("#tab_body").css({"display":"none"});
		$("#tab_main").css({"display":"block","overflow":"auto","width":"100%"});
		$("#tab_main").html(aHtml);	
		$("#tab_main").animate({left:"0"},"fast");

		$(".city-list").css({"width":"100%","overflow":"hidden","color":"#6e6e6e","font-size":"16px","display":"inline-block","padding-bottom":"5px","width":"100%"});
		$(".city-letter").css({"color":"#6e6e6e","font-size":"16px","display":"inline-block","padding-top":"15px","padding-bottom":"5px","border-bottom":"1px solid #e8ecf1","width":"100%"});
		$(".city-list p").css({"color":"#afafaf","width":"95%","height":"50px","line-height":"50px","border-bottom":"1px solid #e8ecf1","cursor":"pointer"});
        $(".letter ul").css({"list-style-type":"none"});
        $(".letter ul li a").css({"text-decoration":"none","color":"#1296db"});

		$(".weui-search-bar__form").click(function() {
			$(".weui-search-bar").addClass("weui-search-bar_focusing");
			$(".container").css("display","none");
		});
		
		$("#searchCancel").click(function() {
			$(".weui-search-bar").removeClass("weui-search-bar_focusing");
			$(".container").css("display","block");
		});

		$("#searchBar").find("#searchClear").click(function(){
			$("#search_show").empty();
			$("input[type='search']").val("");									
		});

		$("input[type='search']").bind('input porpertychange',function(){
			$("#search_show").empty();
			var theName = $(this).val().trim().replace(/\s+/g, "");
			if (theName.length>0) {
				$('.city-list').find('p').each(function () {
					var searchname1=$(this).attr("data-name");
					var searchname2=$(this).attr("data-shorten");
					var searchname3=$(this).text();
					
					if (searchname1.indexOf(theName)=='0' || searchname2.indexOf(theName)=='0' || searchname3.indexOf(theName)>-1 ) {
						var name=$(this).text();
						$("#search_show").append('<div class="weui-cell">'
				                                +'    <div class="weui-cell_bd weui-cell_primary">'
				                                +'        <p>'+name+'</p>'
				                                +'    </div>'	
				                                +'</div>'
						);
					}
				});

				$("#search_show").find(".weui-cell").click(function(){
					// $.showLoading();
					var City=$(this).find("p").text();
					console.log(City);
					// map.centerAndZoom(City,11);
					Goback();
					$('#NowCity').html(City);
				
				});
			}            
		});
								
		$('#tab_main').find(".city-list p").click(function() {
			// $.showLoading();
			var City=$(this).text();
			console.log(City);
			Goback();
				$('#NowCity').html(City);

			// map.centerAndZoom(City,11);	
		});	
	});
